### ISSUE TITLE
"Main." prefix added to events from the commandline

### ISSUE THREAD

**Issue by jonisb** [EventGhost/EventGhost#388]
**Describe the bug**
Creating an event via command-line adds a "Main." prefix even though a full event is specified.
"C:\Program Files (x86)\EventGhost\eventghost.exe" -e Keyboard.LShift+F2

This seems to be different to how 0.4 worked, is this intended?

**To Reproduce**
Steps to reproduce the behavior, something like:
1. Run "C:\Program Files (x86)\EventGhost\eventghost.exe" -e Keyboard.LShift+F2
2. "Main.Keyboard.LShift+F2" event is created

**Expected behavior**
"Keyboard.LShift+F2" event is expected

**Screenshots**
https://pasteboard.co/IvcAF9R.bmp

**Additional context**
Question from the forum:
http://www.eventghost.net/forum/viewtopic.php?f=2&t=10359&sid=6b567913494e3e47291887caaddf668d

**EventGhost version**
EvnetGhost Version 0.5.0.-rc6 (2018-12-24)
Windows 10 Pro X64

**Comment by DanEdens** [comment]
You can get around this by using the wildcards * and ? in your trigger.

For example:

`*.LShift+f2`

**Comment by jonisb** [comment]
My main interest is "This seems to be different to how 0.4 worked, is this intended?" and why break comparability and make the command-line events less flexible?

**Comment by kdschlosser** [comment]
There is a goof somewhere I think. it is supposed to evaluate the event string and if there is no "." in it then it will add "Main." to it. I know I was messing around with it quite a bit when I was working with the named pipe and now the socket connection..

I know what has changed!!! the event is no longer created in Cli.py...
I do not have access to the EventGhost github. and Topic seems to have disappeared. I asked @CarsonF  to see if he is able to get a hold of him and I have not had a response from either....

This is what has stalled work on EventGhost. I haven't bothered to do any PR's because they are not going to get tested/merged.

I will slap together something in the time being that the user can run in order to get the expected output they want.

**Comment by kdschlosser** [comment]
ok so it looks like the Main problem has been fixed. it's in RC6

https://github.com/EventGhost/EventGhost/releases/tag/v0.5.0-rc6

**Comment by jonisb** [comment]
Holy shit did I get a scare, rc6 did not load my config after I upgraded and when I checked "C:\Users\jonib\AppData\Roaming\EventGhost" all files ware gone. But I had them in my D: drive so I guess I shouldn't be doing this stuff when I should be sleeping. 😪 

But the important part is I still get the "Main." part in the event and the user was already using  0.5.0.-rc6 when he posted on the forum.

**Comment by DanEdens** [comment]
Changing branchs does that to me all the time.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kdschlosser** [comment]
Oh crap.. I know why!!! I am a ding bat! sheesh.. i forgot that the prefix is the second param in eg.TriggerEvent and the prefix is defaulted to "Main"

**Comment by DanEdens** [comment]
![2019-09-05 09_27_13-](https://user-images.githubusercontent.com/48360111/64351176-7929da80-cfbf-11e9-8d48-cd335a2cf7be.png)
So this is a similar thing, would it be the same fix?
This is the "add events" window, I modded it a bit for my purposes.
but it inserts as "System.*.job?"

![2019-09-05 09_28_42-EventGhost WIP - general ai 0 3 4](https://user-imagesgithubusercontent.com/48360111/64351288-a8d8e280-cfbf-11e9-9ec6-a2652df92c74.png)

**Comment by kdschlosser** [comment]
thats because you have the system plugin highlighted when you made the event.

**Comment by DanEdens** [comment]
yeah i know, but I can't for the life of me figure out adding addition lists besides understanding I should be doing so in a whole new plugin that injects it's own list. I'll get there lol, feel like I'm getting closer to understanding the picture.

What i'd really love to do is just find where it gets the name of the plugin to insert before lastSelectedTreeItem and replace "system" with " * " 
Don't worry about it I'll find it haha
